<?php
$presets['boxed_dark'] = array (
  'appearance-copyrights' => '© Dream-Theme.com, 2011-2012',
  'appearance-dt_credits' => '1',
  'misc-show_header_contacts' => '1',
  'misc-contact_address' => '',
  'misc-contact_phone' => '+380 44 100 20 33',
  'misc-contact_email' => 'hello@dream-theme.com',
  'misc-contact_skype' => 'dream.theme',
  'misc-parent_menu_clickable' => '1',
  'misc-analitics_code' => '',
  'main_bg-bg_upload' => '0',
  'divs_and_heads-content_wide_divider_upload' => '0',
  'divs_and_heads-content_wide_divider_repeatx' => '0',
  'divs_and_heads-content_narrow_divider_upload' => '0',
  'divs_and_heads-content_narrow_divider_repeatx' => '0',
  'header_homepage-bg_upload' => '0',
  'header_content-bg_upload' => '0',
  'top_line-bg_upload' => '0',
  'mr_parallax-enable' => '1',
  'mr_parallax-fixed' => '0',
  'first_level-bg_upload' => '0',
  'second_level-bg_upload' => '0',
  'third_level-bg_upload' => '0',
  'forth_level-bg_upload' => '0',
  'footer-bg_upload' => '0',
  'divs_and_heads-footer_wide_divider_upload' => '0',
  'divs_and_heads-footer_wide_divider_repeatx' => '0',
  'divs_and_heads-footer_narrow_divider_upload' => '0',
  'divs_and_heads-footer_narrow_divider_repeatx' => '1',
  'bottom_line-bg_upload' => '0',
  'fonts-enable_cufon' => '1',
  'fonts-upload' => '0',
  'of_generatortest2' => 
  array (
    1 => 
    array (
      'sidebar_name' => 'Default Sidebar',
      'sidebar_desc' => 'Sidebar primary widget area',
    ),
    2 => 
    array (
      'sidebar_name' => 'Default Footer',
      'sidebar_desc' => 'Footer primary widget area',
    ),
    3 => 
    array (
      'sidebar_name' => 'Single post page sidebar',
      'sidebar_desc' => '',
    ),
    4 => 
    array (
      'sidebar_name' => 'Single catalog item page sidebar',
      'sidebar_desc' => '',
    ),
    5 => 
    array (
      'sidebar_name' => 'Single post page footer',
      'sidebar_desc' => '',
    ),
    6 => 
    array (
      'sidebar_name' => 'Single catalog item page footer',
      'sidebar_desc' => '',
    ),
    7 => 
    array (
      'sidebar_name' => 'Single portfolio project page footer',
      'sidebar_desc' => '',
    ),
    8 => 
    array (
      'sidebar_name' => '2',
      'sidebar_desc' => '',
    ),
    9 => 
    array (
      'sidebar_name' => '3',
      'sidebar_desc' => '',
    ),
    10 => 
    array (
      'sidebar_name' => '4',
      'sidebar_desc' => '',
    ),
    11 => 
    array (
      'sidebar_name' => '5',
      'sidebar_desc' => '',
    ),
    12 => 
    array (
      'sidebar_name' => '6',
      'sidebar_desc' => '',
    ),
    13 => 
    array (
      'sidebar_name' => '7',
      'sidebar_desc' => '',
    ),
    14 => 
    array (
      'sidebar_name' => '8',
      'sidebar_desc' => '',
    ),
    15 => 
    array (
      'sidebar_name' => '9',
      'sidebar_desc' => '',
    ),
    16 => 
    array (
      'sidebar_name' => '10',
      'sidebar_desc' => '',
    ),
    17 => 
    array (
      'sidebar_name' => '11',
      'sidebar_desc' => '',
    ),
    18 => 
    array (
      'sidebar_name' => '12',
      'sidebar_desc' => '',
    ),
    19 => 
    array (
      'sidebar_name' => '13',
      'sidebar_desc' => '',
    ),
    20 => 
    array (
      'sidebar_name' => '14',
      'sidebar_desc' => '',
    ),
    21 => 
    array (
      'sidebar_name' => '15',
      'sidebar_desc' => '',
    ),
  ),
  'social_icons' => 
  array (
    'vimeo' => 
    array (
      'link' => 'vimeo_link',
      'src' => '/images/soc-ico/vimeo.png',
    ),
    'facebook' => 
    array (
      'link' => 'faceboock_link',
      'src' => '/images/soc-ico/facebook.png',
    ),
    'twitter' => 
    array (
      'link' => 'twitter_link',
      'src' => '/images/soc-ico/twitter.png',
    ),
  ),
  'of-preset' => 'boxed_dark',
  'captcha_hide_register' => '0',
  'captcha_math_action_minus' => '1',
  'captcha_math_action_increase' => '1',
  'captcha_difficulty_number' => '1',
  'captcha_difficulty_word' => '1',
  'appearance-favicon' => '',
  'misc-hide_next_prev_post' => '0',
  'misc-hide_next_prev_portfolio' => '0',
  'main_bg-bg_fixed' => '0',
  'appearance-header_logo' => '/wp-content/themes/dt-cardamon/images/backgrounds/branding/dark_logo-top.png',
  'appearance-header_logo_position' => 'left',
  'appearance-footer_logo' => '/wp-content/themes/dt-cardamon/images/backgrounds/branding/dark_logo-bottom.png',
  'appearance-footer_logo_position' => 'left',
  'main_bg-bg_color' => '#f4f4f4',
  'background-bg_image' => '/images/backgrounds/content/pattern-main/full/dark_pattern-main.jpg',
  'main_bg-bg_repeat' => 'repeat',
  'main_bg-bg_vertical_pos' => 'top',
  'main_bg-bg_horizontal_pos' => 'center',
  'divs_and_heads-content_wide_divider' => '/images/backgrounds/content/div-big/full/dark_div-big.png',
  'divs_and_heads-content_narrow_divider' => '/images/backgrounds/content/div-small/full/dark_div-small.png',
  'widgetcodes-bg_color' => '#ffffff',
  'widgetcodes-bg_opacity' => 11,
  'header_homepage-bg_image' => '/images/backgrounds/header/art-header-main/full/dark_art-header-main.png',
  'header_homepage-bg_repeat' => 'repeat-y',
  'header_homepage-bg_vertical_pos' => 'top',
  'header_homepage-bg_horizontal_pos' => 'center',
  'header_content-bg_image' => '/images/backgrounds/header/art-header-inner/full/dark_art-header-inner.png',
  'header_content-bg_repeat' => 'repeat-y',
  'header_content-bg_vertical_pos' => 'top',
  'header_content-bg_horizontal_pos' => 'center',
  'contact-bg_color' => '#ffffff',
  'contact-bg_opacity' => 11,
  'top_line-bg_color' => '#ffffff',
  'top_line-bg_opacity' => 0,
  'top_line-bg_image' => '/images/backgrounds/header/line-top/full/dark_line-top.png',
  'top_line-bg_repeat' => 'no-repeat',
  'top_line-bg_vertical_pos' => 'top',
  'top_line-bg_horizontal_pos' => 'center',
  'mr_parallax-animate' => 'home',
  'mr_parallax-show' => 'home',
  'first_level-bg_image' => 'none',
  'first_level-bg_repeat' => 'repeat-x',
  'first_level-bg_horizontal_pos' => 'center',
  'second_level-bg_image' => 'none',
  'second_level-bg_repeat' => 'repeat-x',
  'second_level-bg_horizontal_pos' => 'center',
  'third_level-bg_image' => 'none',
  'third_level-bg_repeat' => 'repeat-x',
  'third_level-bg_horizontal_pos' => 'center',
  'forth_level-bg_image' => 'none',
  'forth_level-bg_repeat' => 'no-repeat',
  'forth_level-bg_horizontal_pos' => 'center',
  'footer-bg_color' => '',
  'footer-bg_image' => '/images/backgrounds/footer/pattern-footer/full/dark_pattern-footer.png',
  'footer-bg_repeat' => 'repeat-y',
  'footer-bg_vertical_pos' => 'center',
  'footer-bg_horizontal_pos' => 'center',
  'divs_and_heads-footer_wide_divider' => '/images/backgrounds/footer/line-decor/full/dark_line-decor.png',
  'divs_and_heads-footer_narrow_divider' => '/images/backgrounds/footer/div-footer/full/dark_div-footer.png',
  'widgetcodes_footer-bg_color' => '#ffffff',
  'widgetcodes_footer-bg_opacity' => 10,
  'bottom_line-bg_color' => '#2a2a2a',
  'bottom_line-bg_opacity' => 0,
  'bottom_line-bg_image' => '/images/backgrounds/footer/line-bottom/full/dark_line-bottom.png',
  'bottom_line-bg_repeat' => 'no-repeat',
  'bottom_line-bg_vertical_pos' => 'bottom',
  'bottom_line-bg_horizontal_pos' => 'center',
  'fonts-font_family' => 'Arial',
  'fonts-links_color' => '#0f0f0f',
  'fonts-hover_color' => '#b84588',
  'fonts_content-topline_color' => '#f0f0f0',
  'fonts_content-topline_shadow_color' => '#000000',
  'fonts_content-contacts_color' => '#d7dadb',
  'fonts_content-contacts_shadow_color' => '#000000',
  'fonts_content-primary_color' => '#c1c5c7',
  'fonts_content-primary_shadow_color' => '#000000',
  'fonts_content-secondary_color' => '#ef82ca',
  'fonts_content-secondary_shadow_color' => '#000000',
  'fonts_footer-primary_color' => '#f0f0f0',
  'fonts_footer-primary_shadow_color' => '#000000',
  'fonts_footer-secondary_color' => '#ef82ca',
  'fonts_footer-secondary_shadow_color' => '#000000',
  'fonts_content-bottomline_color' => '#f0f0f0',
  'fonts_content-bottomline_shadow_color' => '#000000',
  'fonts-list' => '/js/fonts/Playball.font.js',
  'fonts-headers_size_h1' => '35',
  'fonts-headers_size_h2' => '27',
  'fonts-headers_size_h3' => '21',
  'fonts-headers_size_h4' => '18',
  'fonts-headers_size_h5' => '16',
  'fonts-headers_size_h6' => '14',
  'fonts_content-headers_top_color' => '#ffffff',
  'fonts_content-headers_bottom_color' => '#aaabad',
  'fonts_content-headers_shadow_color' => '#000000',
  'fonts_footer-headers_top_color' => '#ffffff',
  'fonts_footer-headers_bottom_color' => '#aaabad',
  'fonts_footer-headers_shadow_color' => '#000000',
  'layout_paginator_show_all_checkbox' => '0',
  'breadcrumbs_checkbox' => '0',
  'menu_parent_menu_clickable_checkbox' => '1',
  'fonts_enable_cufon_checkbox' => '0',
  'fonts_enable_custom_checkbox' => '0',
  'cc_show_credits_checkbox' => '1',
  'lv1_custom_bg_checkbox' => '0',
  'lv2_custom_bg_checkbox' => '0',
  'lv3_custom_bg_checkbox' => '0',
  'decor_corner_checkbox' => '1',
  'custom_decor_corner_checkbox' => '0',
  'top_custom_bg_checkbox' => '0',
  'body_custom_bg_checkbox' => '0',
  'body_fix_bg_checkbox' => '0',
  'misc_aim__png_checkbox' => '0',
  'misc_behance__png_checkbox' => '0',
  'misc_blogger__png_checkbox' => '0',
  'misc_cargo__png_checkbox' => '0',
  'misc_design_float__png_checkbox' => '0',
  'misc_delicious__png_checkbox' => '0',
  'misc_designmoo__png_checkbox' => '0',
  'misc_deviantart__png_checkbox' => '0',
  'misc_digg__png_checkbox' => '0',
  'misc_dribbble__png_checkbox' => '0',
  'misc_evernote__png_checkbox' => '0',
  'misc_facebook__png_checkbox' => '0',
  'misc_forrst__png_checkbox' => '0',
  'misc_flickr__png_checkbox' => '0',
  'misc_google__png_checkbox' => '0',
  'misc_google_buzz__png_checkbox' => '0',
  'misc_last_fm__png_checkbox' => '0',
  'misc_linkedin__png_checkbox' => '0',
  'misc_myscape__png_checkbox' => '0',
  'misc_open_id__png_checkbox' => '0',
  'misc_paypal__png_checkbox' => '0',
  'misc_picasa__png_checkbox' => '0',
  'misc_rss__png_checkbox' => '0',
  'misc_share_this__png_checkbox' => '0',
  'misc_skype__png_checkbox' => '0',
  'misc_thumblr__png_checkbox' => '0',
  'misc_twitter__png_checkbox' => '0',
  'misc_vimeo__png_checkbox' => '0',
  'misc_wordpress__png_checkbox' => '0',
  'misc_yahoo__png_checkbox' => '0',
  'misc_yelp__png_checkbox' => '0',
  'misc_youtube__png_checkbox' => '0',
  'misc_like_panel_checkbox' => '0',
  'misc_display_like_panel_checkbox' => '0',
  'misc_fixed_like_panel_checkbox' => '0',
  'appearance_favicon_uploader' => '',
  'appearance_logo_uploader' => '',
  'fonts_select' => '',
  'fonts_custom_uploader' => '',
  'cc_copy_info_textarea' => '',
  'wf_select' => 'every',
  'lv1_back_color_colorpicker' => '#EDEDED',
  'lv1_custom_db_uploader' => '',
  'lv1_repeat_select' => 'repeat',
  'lv1_vert_position_select' => 'center',
  'lv1_horiz_position_select' => 'left',
  'lv2_custom_db_uploader' => '',
  'lv2_repeat_select' => 'repeat',
  'lv2_vert_position_select' => 'center',
  'lv2_horiz_position_select' => 'left',
  'lv3_custom_db_uploader' => '',
  'lv3_repeat_select' => 'repeat-x',
  'lv3_vert_position_select' => 'center',
  'lv3_horiz_position_select' => 'left',
  'custom_decor_corner_uploader' => '',
  'misc_colour_schema_select' => 'pink',
  'top_back_color_colorpicker' => '#EDEDED',
  'top_custom_db_uploader' => '',
  'top_repeat_select' => 'repeat',
  'top_vert_position_select' => 'top',
  'top_horiz_position_select' => 'left',
  'body_back_color_colorpicker' => '#EDEDED',
  'body_custom_db_uploader' => '',
  'body_repeat_select' => 'repeat',
  'body_vert_position_select' => 'top',
  'body_horiz_position_select' => 'left',
  'misc_a_code_textarea' => '',
  'misc_aim__png_text' => '',
  'misc_behance__png_text' => '',
  'misc_blogger__png_text' => '',
  'misc_cargo__png_text' => '',
  'misc_design_float__png_text' => '',
  'misc_delicious__png_text' => '',
  'misc_designmoo__png_text' => '',
  'misc_deviantart__png_text' => '',
  'misc_digg__png_text' => '',
  'misc_dribbble__png_text' => '',
  'misc_evernote__png_text' => '',
  'misc_facebook__png_text' => '',
  'misc_forrst__png_text' => '',
  'misc_flickr__png_text' => '',
  'misc_google__png_text' => '',
  'misc_google_buzz__png_text' => '',
  'misc_last_fm__png_text' => '',
  'misc_linkedin__png_text' => '',
  'misc_myscape__png_text' => '',
  'misc_open_id__png_text' => '',
  'misc_paypal__png_text' => '',
  'misc_picasa__png_text' => '',
  'misc_rss__png_text' => '',
  'misc_share_this__png_text' => '',
  'misc_skype__png_text' => '',
  'misc_thumblr__png_text' => '',
  'misc_twitter__png_text' => '',
  'misc_vimeo__png_text' => '',
  'misc_wordpress__png_text' => '',
  'misc_yahoo__png_text' => '',
  'misc_yelp__png_text' => '',
  'misc_youtube__png_text' => '',
  'misc_likes_code_textarea' => '',
  'lv1_back_images' => '',
  'lv2_back_images' => '',
  'lv3_back_images' => '',
  'top_back_images' => '',
  'body_back_images' => '',
  'misc_AIM__png_checkbox' => '0',
  'misc_AIM__png_text' => '',
  'misc_Behance__png_checkbox' => '0',
  'misc_Behance__png_text' => '',
  'misc_Blogger__png_checkbox' => '0',
  'misc_Blogger__png_text' => '',
  'misc_Cargo__png_checkbox' => '0',
  'misc_Cargo__png_text' => '',
  'misc_Design_Float__png_checkbox' => '0',
  'misc_Design_Float__png_text' => '',
  'misc_Delicious__png_checkbox' => '0',
  'misc_Delicious__png_text' => '',
  'misc_DesignMoo__png_checkbox' => '0',
  'misc_DesignMoo__png_text' => '',
  'misc_DeviantART__png_checkbox' => '0',
  'misc_DeviantART__png_text' => '',
  'misc_Digg__png_checkbox' => '0',
  'misc_Digg__png_text' => '',
  'misc_Dribbble__png_checkbox' => '0',
  'misc_Dribbble__png_text' => '',
  'misc_Evernote__png_checkbox' => '0',
  'misc_Evernote__png_text' => '',
  'misc_Facebook__png_checkbox' => '0',
  'misc_Facebook__png_text' => '',
  'misc_Forrst__png_checkbox' => '0',
  'misc_Forrst__png_text' => '',
  'misc_Flickr__png_checkbox' => '0',
  'misc_Flickr__png_text' => '',
  'misc_Google__png_checkbox' => '0',
  'misc_Google__png_text' => '',
  'misc_Google_Buzz__png_checkbox' => '0',
  'misc_Google_Buzz__png_text' => '',
  'misc_Last_FM__png_checkbox' => '0',
  'misc_Last_FM__png_text' => '',
  'misc_Linkedin__png_checkbox' => '0',
  'misc_Linkedin__png_text' => '',
  'misc_MyScape__png_checkbox' => '0',
  'misc_MyScape__png_text' => '',
  'misc_Open_ID__png_checkbox' => '0',
  'misc_Open_ID__png_text' => '',
  'misc_PayPal__png_checkbox' => '0',
  'misc_PayPal__png_text' => '',
  'misc_Picasa__png_checkbox' => '0',
  'misc_Picasa__png_text' => '',
  'misc_RSS__png_checkbox' => '0',
  'misc_RSS__png_text' => '',
  'misc_Share_This__png_checkbox' => '0',
  'misc_Share_This__png_text' => '',
  'misc_Skype__png_checkbox' => '0',
  'misc_Skype__png_text' => '',
  'misc_Thumblr__png_checkbox' => '0',
  'misc_Thumblr__png_text' => '',
  'misc_Twitter__png_checkbox' => '0',
  'misc_Twitter__png_text' => '',
  'misc_Vimeo__png_checkbox' => '0',
  'misc_Vimeo__png_text' => '',
  'misc_Wordpress__png_checkbox' => '0',
  'misc_Wordpress__png_text' => '',
  'misc_Yahoo__png_checkbox' => '0',
  'misc_Yahoo__png_text' => '',
  'misc_Yelp__png_checkbox' => '0',
  'misc_Yelp__png_text' => '',
  'misc_Youtube__png_checkbox' => '0',
  'misc_Youtube__png_text' => '',
  'testingg-checkbox' => '0',
  'testingg_checkbox' => '0',
  'of_generator_test' => 
  array (
  ),
  'divs_and_heads-content_header_under' => '/images/dividers/content/underline/full/dot-line.png',
  'divs_and_heads-content_header_under_upload' => '0',
  'divs_and_heads-content_header_under_repeatx' => '1',
  'divs_and_heads-footer_header_under' => 'none',
  'divs_and_heads-footer_header_under_upload' => '0',
  'divs_and_heads-footer_header_under_repeatx' => '1',
  'main_bg-bg_custom' => '',
  'divs_and_heads-content_wide_divider_custom' => '',
  'divs_and_heads-content_narrow_divider_custom' => '',
  'header_homepage-bg_custom' => '',
  'header_content-bg_custom' => '',
  'top_line-bg_custom' => '',
  'first_level-bg_custom' => '',
  'second_level-bg_custom' => '',
  'third_level-bg_custom' => '',
  'forth_level-bg_custom' => '',
  'footer-bg_custom' => '',
  'divs_and_heads-footer_narrow_divider_custom' => '',
  'bottom_line-bg_custom' => '',
  'fonts-custom' => '',
  'divs_and_heads-footer_wide_divider_custom' => ''
);
?>